language: php
php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  allow_failures:
    - nightly
  include:
    - nightly

git:
  depth: 1

cache:
  timeout: 691200
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --quiet --no-interaction --no-ansi --no-progress --optimize-autoloader --dev --prefer-dist --no-suggest --ignore-platform-reqs

script:
  - vendor/bin/phpcs --standard=PSR2 ./src
  - vendor/bin/codecept build
  - vendor/bin/codecept run

notifications:
  email:
    recipients:
      - travis-ci@twistersfury.com
    on_success: change
    on_failure: always
